//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sw.Hospital.HealthExaminationSystem.EntityFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sw.Hospital.HealthExaminationSystem.EntityFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 行政区划代码|单位名称
        ///110000|北京市
        ///110101|东城区
        ///110102|西城区
        ///110105|朝阳区
        ///110106|丰台区
        ///110107|石景山区
        ///110108|海淀区
        ///110109|门头沟区
        ///110111|房山区
        ///110112|通州区
        ///110113|顺义区
        ///110114|昌平区
        ///110115|大兴区
        ///110116|怀柔区
        ///110117|平谷区
        ///110118|密云区
        ///110119|延庆区
        ///120000|天津市
        ///120101|和平区
        ///120102|河东区
        ///120103|河西区
        ///120104|南开区
        ///120105|河北区
        ///120106|红桥区
        ///120110|东丽区
        ///120111|西青区
        ///120112|津南区
        ///120113|北辰区
        ///120114|武清区
        ///120115|宝坻区
        ///120116|滨海新区
        ///120117|宁河区
        ///120118|静海区
        ///120119|蓟州区
        ///130000|河北省
        ///130100|石家庄市
        ///130102|长安区
        ///130104|桥西区
        ///130105|新华区
        ///130107|井陉矿区
        ///130108|裕华区
        ///13 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AdministrativeDivision {
            get {
                return ResourceManager.GetString("AdministrativeDivision", resourceCulture);
            }
        }
    }
}
