//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace DZFP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SalesWebServiceSoapBinding", Namespace="http://service.jsaisino.com")]
    public partial class SalesWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback orderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback invoiceCardInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback invoiceHZTZDXZOperationCompleted;
        
        private System.Threading.SendOrPostCallback invoiceZFOperationCompleted;
        
        private System.Threading.SendOrPostCallback invoiceKJOperationCompleted;
        
        private System.Threading.SendOrPostCallback invoiceHZTZDCXOperationCompleted;
        
        private System.Threading.SendOrPostCallback invoiceDQHMCXOperationCompleted;
        
        private System.Threading.SendOrPostCallback invoiceHZTZDSQOperationCompleted;
        
        private System.Threading.SendOrPostCallback invoiceKCOperationCompleted;
        
        /// <remarks/>
        public SalesWebService() {
            this.Url = "http://10.10.1.102:8081/stms_sales/smtSales/Services/salesWS";
        }
        
        /// <remarks/>
        public event orderInfoCompletedEventHandler orderInfoCompleted;
        
        /// <remarks/>
        public event invoiceCardInfoCompletedEventHandler invoiceCardInfoCompleted;
        
        /// <remarks/>
        public event invoiceHZTZDXZCompletedEventHandler invoiceHZTZDXZCompleted;
        
        /// <remarks/>
        public event invoiceZFCompletedEventHandler invoiceZFCompleted;
        
        /// <remarks/>
        public event invoiceKJCompletedEventHandler invoiceKJCompleted;
        
        /// <remarks/>
        public event invoiceHZTZDCXCompletedEventHandler invoiceHZTZDCXCompleted;
        
        /// <remarks/>
        public event invoiceDQHMCXCompletedEventHandler invoiceDQHMCXCompleted;
        
        /// <remarks/>
        public event invoiceHZTZDSQCompletedEventHandler invoiceHZTZDSQCompleted;
        
        /// <remarks/>
        public event invoiceKCCompletedEventHandler invoiceKCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.jsaisino.com", ResponseNamespace="http://service.jsaisino.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseJSON")]
        public string orderInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string requestJSON) {
            object[] results = this.Invoke("orderInfo", new object[] {
                        requestJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginorderInfo(string requestJSON, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("orderInfo", new object[] {
                        requestJSON}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndorderInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void orderInfoAsync(string requestJSON) {
            this.orderInfoAsync(requestJSON, null);
        }
        
        /// <remarks/>
        public void orderInfoAsync(string requestJSON, object userState) {
            if ((this.orderInfoOperationCompleted == null)) {
                this.orderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnorderInfoOperationCompleted);
            }
            this.InvokeAsync("orderInfo", new object[] {
                        requestJSON}, this.orderInfoOperationCompleted, userState);
        }
        
        private void OnorderInfoOperationCompleted(object arg) {
            if ((this.orderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.orderInfoCompleted(this, new orderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.jsaisino.com", ResponseNamespace="http://service.jsaisino.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseJSON")]
        public string invoiceCardInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string requestJSON) {
            object[] results = this.Invoke("invoiceCardInfo", new object[] {
                        requestJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininvoiceCardInfo(string requestJSON, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("invoiceCardInfo", new object[] {
                        requestJSON}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinvoiceCardInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invoiceCardInfoAsync(string requestJSON) {
            this.invoiceCardInfoAsync(requestJSON, null);
        }
        
        /// <remarks/>
        public void invoiceCardInfoAsync(string requestJSON, object userState) {
            if ((this.invoiceCardInfoOperationCompleted == null)) {
                this.invoiceCardInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvoiceCardInfoOperationCompleted);
            }
            this.InvokeAsync("invoiceCardInfo", new object[] {
                        requestJSON}, this.invoiceCardInfoOperationCompleted, userState);
        }
        
        private void OninvoiceCardInfoOperationCompleted(object arg) {
            if ((this.invoiceCardInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invoiceCardInfoCompleted(this, new invoiceCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.jsaisino.com", ResponseNamespace="http://service.jsaisino.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseJSON")]
        public string invoiceHZTZDXZ([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string requestJSON) {
            object[] results = this.Invoke("invoiceHZTZDXZ", new object[] {
                        requestJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininvoiceHZTZDXZ(string requestJSON, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("invoiceHZTZDXZ", new object[] {
                        requestJSON}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinvoiceHZTZDXZ(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invoiceHZTZDXZAsync(string requestJSON) {
            this.invoiceHZTZDXZAsync(requestJSON, null);
        }
        
        /// <remarks/>
        public void invoiceHZTZDXZAsync(string requestJSON, object userState) {
            if ((this.invoiceHZTZDXZOperationCompleted == null)) {
                this.invoiceHZTZDXZOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvoiceHZTZDXZOperationCompleted);
            }
            this.InvokeAsync("invoiceHZTZDXZ", new object[] {
                        requestJSON}, this.invoiceHZTZDXZOperationCompleted, userState);
        }
        
        private void OninvoiceHZTZDXZOperationCompleted(object arg) {
            if ((this.invoiceHZTZDXZCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invoiceHZTZDXZCompleted(this, new invoiceHZTZDXZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.jsaisino.com", ResponseNamespace="http://service.jsaisino.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseJSON")]
        public string invoiceZF([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string requestJSON) {
            object[] results = this.Invoke("invoiceZF", new object[] {
                        requestJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininvoiceZF(string requestJSON, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("invoiceZF", new object[] {
                        requestJSON}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinvoiceZF(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invoiceZFAsync(string requestJSON) {
            this.invoiceZFAsync(requestJSON, null);
        }
        
        /// <remarks/>
        public void invoiceZFAsync(string requestJSON, object userState) {
            if ((this.invoiceZFOperationCompleted == null)) {
                this.invoiceZFOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvoiceZFOperationCompleted);
            }
            this.InvokeAsync("invoiceZF", new object[] {
                        requestJSON}, this.invoiceZFOperationCompleted, userState);
        }
        
        private void OninvoiceZFOperationCompleted(object arg) {
            if ((this.invoiceZFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invoiceZFCompleted(this, new invoiceZFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.jsaisino.com", ResponseNamespace="http://service.jsaisino.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseJSON")]
        public string invoiceKJ([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string requestJSON) {
            object[] results = this.Invoke("invoiceKJ", new object[] {
                        requestJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininvoiceKJ(string requestJSON, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("invoiceKJ", new object[] {
                        requestJSON}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinvoiceKJ(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invoiceKJAsync(string requestJSON) {
            this.invoiceKJAsync(requestJSON, null);
        }
        
        /// <remarks/>
        public void invoiceKJAsync(string requestJSON, object userState) {
            if ((this.invoiceKJOperationCompleted == null)) {
                this.invoiceKJOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvoiceKJOperationCompleted);
            }
            this.InvokeAsync("invoiceKJ", new object[] {
                        requestJSON}, this.invoiceKJOperationCompleted, userState);
        }
        
        private void OninvoiceKJOperationCompleted(object arg) {
            if ((this.invoiceKJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invoiceKJCompleted(this, new invoiceKJCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.jsaisino.com", ResponseNamespace="http://service.jsaisino.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseJSON")]
        public string invoiceHZTZDCX([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string requestJSON) {
            object[] results = this.Invoke("invoiceHZTZDCX", new object[] {
                        requestJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininvoiceHZTZDCX(string requestJSON, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("invoiceHZTZDCX", new object[] {
                        requestJSON}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinvoiceHZTZDCX(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invoiceHZTZDCXAsync(string requestJSON) {
            this.invoiceHZTZDCXAsync(requestJSON, null);
        }
        
        /// <remarks/>
        public void invoiceHZTZDCXAsync(string requestJSON, object userState) {
            if ((this.invoiceHZTZDCXOperationCompleted == null)) {
                this.invoiceHZTZDCXOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvoiceHZTZDCXOperationCompleted);
            }
            this.InvokeAsync("invoiceHZTZDCX", new object[] {
                        requestJSON}, this.invoiceHZTZDCXOperationCompleted, userState);
        }
        
        private void OninvoiceHZTZDCXOperationCompleted(object arg) {
            if ((this.invoiceHZTZDCXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invoiceHZTZDCXCompleted(this, new invoiceHZTZDCXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.jsaisino.com", ResponseNamespace="http://service.jsaisino.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseJSON")]
        public string invoiceDQHMCX([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string requestJSON) {
            object[] results = this.Invoke("invoiceDQHMCX", new object[] {
                        requestJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininvoiceDQHMCX(string requestJSON, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("invoiceDQHMCX", new object[] {
                        requestJSON}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinvoiceDQHMCX(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invoiceDQHMCXAsync(string requestJSON) {
            this.invoiceDQHMCXAsync(requestJSON, null);
        }
        
        /// <remarks/>
        public void invoiceDQHMCXAsync(string requestJSON, object userState) {
            if ((this.invoiceDQHMCXOperationCompleted == null)) {
                this.invoiceDQHMCXOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvoiceDQHMCXOperationCompleted);
            }
            this.InvokeAsync("invoiceDQHMCX", new object[] {
                        requestJSON}, this.invoiceDQHMCXOperationCompleted, userState);
        }
        
        private void OninvoiceDQHMCXOperationCompleted(object arg) {
            if ((this.invoiceDQHMCXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invoiceDQHMCXCompleted(this, new invoiceDQHMCXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.jsaisino.com", ResponseNamespace="http://service.jsaisino.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseJSON")]
        public string invoiceHZTZDSQ([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string requestJSON) {
            object[] results = this.Invoke("invoiceHZTZDSQ", new object[] {
                        requestJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininvoiceHZTZDSQ(string requestJSON, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("invoiceHZTZDSQ", new object[] {
                        requestJSON}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinvoiceHZTZDSQ(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invoiceHZTZDSQAsync(string requestJSON) {
            this.invoiceHZTZDSQAsync(requestJSON, null);
        }
        
        /// <remarks/>
        public void invoiceHZTZDSQAsync(string requestJSON, object userState) {
            if ((this.invoiceHZTZDSQOperationCompleted == null)) {
                this.invoiceHZTZDSQOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvoiceHZTZDSQOperationCompleted);
            }
            this.InvokeAsync("invoiceHZTZDSQ", new object[] {
                        requestJSON}, this.invoiceHZTZDSQOperationCompleted, userState);
        }
        
        private void OninvoiceHZTZDSQOperationCompleted(object arg) {
            if ((this.invoiceHZTZDSQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invoiceHZTZDSQCompleted(this, new invoiceHZTZDSQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.jsaisino.com", ResponseNamespace="http://service.jsaisino.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseJSON")]
        public string invoiceKC([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string requestJSON) {
            object[] results = this.Invoke("invoiceKC", new object[] {
                        requestJSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegininvoiceKC(string requestJSON, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("invoiceKC", new object[] {
                        requestJSON}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndinvoiceKC(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void invoiceKCAsync(string requestJSON) {
            this.invoiceKCAsync(requestJSON, null);
        }
        
        /// <remarks/>
        public void invoiceKCAsync(string requestJSON, object userState) {
            if ((this.invoiceKCOperationCompleted == null)) {
                this.invoiceKCOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvoiceKCOperationCompleted);
            }
            this.InvokeAsync("invoiceKC", new object[] {
                        requestJSON}, this.invoiceKCOperationCompleted, userState);
        }
        
        private void OninvoiceKCOperationCompleted(object arg) {
            if ((this.invoiceKCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invoiceKCCompleted(this, new invoiceKCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void orderInfoCompletedEventHandler(object sender, orderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class orderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal orderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void invoiceCardInfoCompletedEventHandler(object sender, invoiceCardInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invoiceCardInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invoiceCardInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void invoiceHZTZDXZCompletedEventHandler(object sender, invoiceHZTZDXZCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invoiceHZTZDXZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invoiceHZTZDXZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void invoiceZFCompletedEventHandler(object sender, invoiceZFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invoiceZFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invoiceZFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void invoiceKJCompletedEventHandler(object sender, invoiceKJCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invoiceKJCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invoiceKJCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void invoiceHZTZDCXCompletedEventHandler(object sender, invoiceHZTZDCXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invoiceHZTZDCXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invoiceHZTZDCXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void invoiceDQHMCXCompletedEventHandler(object sender, invoiceDQHMCXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invoiceDQHMCXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invoiceDQHMCXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void invoiceHZTZDSQCompletedEventHandler(object sender, invoiceHZTZDSQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invoiceHZTZDSQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invoiceHZTZDSQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void invoiceKCCompletedEventHandler(object sender, invoiceKCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invoiceKCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invoiceKCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
